name: Tests
on: [push]
 
jobs:
  build:
    name: Run Python Tests and Coverage
    runs-on: ubuntu-latest
 
    steps:
 
    - uses: actions/checkout@v2
 
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: UTC
 
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
 
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install .[test]
 
    - name: Test with pytest, coverage and pylint
      run: |
        pytest tests
        coverage report
        pylint
