name: Tests
on: [push]
 
jobs:
  build:
    name: Run Python Tests and Coverage
    runs-on: ubuntu-latest
 
    steps:
 
    - uses: actions/checkout@v2
 
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
 
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install .[test]
 
    - name: Run pytest and coverage
      run: |
        pytest --cov tests
    
    - name: Check linting
      run: |
        pylint src/
